---

name: Build and Push Image
on: [ push ]
permissions:
  contents: read
  id-token: write
  attestations: write
  packages: write

jobs:
  build:
    name: Build and Push image
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Log in to Docker hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }} 
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: fawkesguyd/fable-backend-auth
    
    - name: Build and push docker image
      id: push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: fawkesguyd/fable-backend-auth:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: index.docker.io/fawkesguyd/fable-backend-auth
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true